### PR TITLE
Optimizes forEach with for loops, delete dead code

### PR DESCRIPTION
**Pull request by jrddunbr**
Optimizes based on Codacy performance warnings.

`.forEach(x .. y) {it -> [...]}` is 3x slower than `for (it in x ..y) { [...] }` loops.

### CODE REVIEW

**Comment by jrddunbr** [comment]
Honestly should consider deleting the thermal code as well because it's flat out broken.. the test always failed to work and was not written properly.

**Review by Grissess — APPROVED** [review]
Although I'm generally not one to change conventions used throughout the source for a _lowering_ issue (id est: a deficiency in the compiler that _can_ be eventually fixed), these are relatively trivial changes, so if CI is happy, I'm fine with it

**Comment by Grissess** [comment]
> Honestly should consider deleting the thermal code as well because it's flat out broken.. the test always failed to work and was not written properly.

I was thinking of doing that myself, @jrddunbr--more power to you if you do :)

**Comment by jrddunbr** [comment]
> > Honestly should consider deleting the thermal code as well because it's flat out broken.. the test always failed to work and was not written properly.
> 
> I was thinking of doing that myself, @jrddunbr--more power to you if you do :)

Will do next PR.

**Comment by jrddunbr** [comment]
> Although I'm generally not one to change conventions used throughout the source for a lowering issue (id est: a deficiency in the compiler that can be eventually fixed), these are relatively trivial changes, so if CI is happy, I'm fine with it

I tend to agree, but I want stuff to be fast :P

**Pull request merged**
